### ISSUE TITLE
SyntaxError: invalid syntax in preprocessing.py

### ISSUE THREAD

**Issue by d80b2t** [AKnightWing/Astronomical-Classification-PLASTICC#1]
I'm trying to run the preprocessing.py code. 
However, when I try, I get: 

> python preprocessing.py 
  File "preprocessing.py", line 20
    if (os.path.isfile(fr"{pickle_location}\{mainfilename}_3d_pickle")
                                                                    ^
SyntaxError: invalid syntax

**Comment by sidchaini** [comment]
Thank you for opening this issue. Could you let me know the operating system and python version you're using to run this code? We wrote this on a Windows system using Python 3.7 and didn't bother to generalise it to other operating systems. I would like to apologise for this. I'll fix it soon, and let you know once it's done.

**Comment by sidchaini** [comment]
Closing this issue, as the necessary changes have been made. Thank you for contributing!
